### PR TITLE
Fix nextcloud-vue Actions and config update

### LINKED ISSUE #119: Migrate Actions component use
See https://github.com/juliushaertl/nextcloud-vue-collections/pull/109

### PR DESCRIPTION
**Pull request by skjnldsv**
@juliushaertl 

Close #119 

Maybe we should add compile tests here.
Because current master is broken :)

### CODE REVIEW

File: src/components/CollectionListItem.vue [hunk 1]
```diff
@@ -122,14 +118,8 @@ export default {
 		}
 	},
 	methods: {
-		open() {
```
Comment (skjnldsv) [inline src/components/CollectionListItem.vue]: I removed it, seemed unused :woman_shrugging:
